# Generated by Django 3.0.3 on 2020-03-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
